# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=profile.models.pic_path, verbose_name='Profile Picture'),
        ),
    ]
