# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sfstaff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
    ]
