# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_user_is_sfstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_sfstaff',
        ),
    ]
