# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_remove_user_is_sfstaff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
