# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.EmailField(max_length=30, verbose_name='email address')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('street_address', models.CharField(blank=True, max_length=30, verbose_name='street_address')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='country')),
                ('area_code', models.CharField(blank=True, max_length=3, verbose_name='area code')),
                ('number', models.CharField(blank=True, max_length=7, verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
