# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20170814_0301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together=set([('business', 'employee')]),
        ),
    ]
