# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170814_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
